let nombre = `Emmanuel`;
let apellido = `Corrales`;
let estudiante = `${nombre} ${apellido}`;
let estudianteMayus = estudiante.toUpperCase();
let estudianteMinus = estudiante.toLowerCase();
let estudianteLegth = estudiante.length;
let primeraLetra = nombre.substring(0,1)
let ultimaLetra = apellido.substring(apellido.length -1, apellido.length)
let sinEspacio = estudiante.replace(/ /g,"")
let tieneNombre = estudiante.includes(nombre)
